/* 
 * Dragonfly Model Schema
 *
 * This is the documentation for Dragonfly model schema.
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DragonflySchema;

using System.Reflection;
using Newtonsoft.Json;

namespace DragonflySchema.Test
{
    /// <summary>
    ///  Class for testing Model
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelTests
    {
        // TODO uncomment below to declare an instance variable for Model
        //private Model instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Model
            //instance = new Model();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Model
        /// </summary>
        [Test]
        public void ModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Model
            //Assert.IsInstanceOf(typeof(Model), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Buildings'
        /// </summary>
        [Test]
        public void BuildingsTest()
        {
            // TODO unit test for the property 'Buildings'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ContextShades'
        /// </summary>
        [Test]
        public void ContextShadesTest()
        {
            // TODO unit test for the property 'ContextShades'
        }
        /// <summary>
        /// Test the property 'NorthAngle'
        /// </summary>
        [Test]
        public void NorthAngleTest()
        {
            // TODO unit test for the property 'NorthAngle'
        }
        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Test]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }
        /// <summary>
        /// Test the property 'Tolerance'
        /// </summary>
        [Test]
        public void ToleranceTest()
        {
            // TODO unit test for the property 'Tolerance'
        }
        /// <summary>
        /// Test the property 'AngleTolerance'
        /// </summary>
        [Test]
        public void AngleToleranceTest()
        {
            // TODO unit test for the property 'AngleTolerance'
        }

    }

}
