/* 
 * Dragonfly Model Schema
 *
 * This is the documentation for Dragonfly model schema.
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DragonflySchema;

using System.Reflection;
using Newtonsoft.Json;

namespace DragonflySchema.Test
{
    /// <summary>
    ///  Class for testing RectangularWindows
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RectangularWindowsTests
    {
        // TODO uncomment below to declare an instance variable for RectangularWindows
        //private RectangularWindows instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RectangularWindows
            //instance = new RectangularWindows();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RectangularWindows
        /// </summary>
        [Test]
        public void RectangularWindowsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RectangularWindows
            //Assert.IsInstanceOf(typeof(RectangularWindows), instance);
        }


        /// <summary>
        /// Test the property 'Origins'
        /// </summary>
        [Test]
        public void OriginsTest()
        {
            // TODO unit test for the property 'Origins'
        }
        /// <summary>
        /// Test the property 'Widths'
        /// </summary>
        [Test]
        public void WidthsTest()
        {
            // TODO unit test for the property 'Widths'
        }
        /// <summary>
        /// Test the property 'Heights'
        /// </summary>
        [Test]
        public void HeightsTest()
        {
            // TODO unit test for the property 'Heights'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
