/* 
 * Dragonfly Model Schema
 *
 * This is the documentation for Dragonfly model schema.
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DragonflySchema;

using System.Reflection;
using Newtonsoft.Json;

namespace DragonflySchema.Test
{
    /// <summary>
    ///  Class for testing SetpointAbridged
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetpointAbridgedTests
    {
        // TODO uncomment below to declare an instance variable for SetpointAbridged
        //private SetpointAbridged instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SetpointAbridged
            //instance = new SetpointAbridged();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SetpointAbridged
        /// </summary>
        [Test]
        public void SetpointAbridgedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SetpointAbridged
            //Assert.IsInstanceOf(typeof(SetpointAbridged), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CoolingSchedule'
        /// </summary>
        [Test]
        public void CoolingScheduleTest()
        {
            // TODO unit test for the property 'CoolingSchedule'
        }
        /// <summary>
        /// Test the property 'HeatingSchedule'
        /// </summary>
        [Test]
        public void HeatingScheduleTest()
        {
            // TODO unit test for the property 'HeatingSchedule'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'HumidifyingSchedule'
        /// </summary>
        [Test]
        public void HumidifyingScheduleTest()
        {
            // TODO unit test for the property 'HumidifyingSchedule'
        }
        /// <summary>
        /// Test the property 'DehumidifyingSchedule'
        /// </summary>
        [Test]
        public void DehumidifyingScheduleTest()
        {
            // TODO unit test for the property 'DehumidifyingSchedule'
        }

    }

}
