/* 
 * Dragonfly Model Schema
 *
 * This is the documentation for Dragonfly model schema.
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DragonflySchema;

using System.Reflection;
using Newtonsoft.Json;

namespace DragonflySchema.Test
{
    /// <summary>
    ///  Class for testing Story
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StoryTests
    {
        // TODO uncomment below to declare an instance variable for Story
        //private Story instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Story
            //instance = new Story();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Story
        /// </summary>
        [Test]
        public void StoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Story
            //Assert.IsInstanceOf(typeof(Story), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Room2ds'
        /// </summary>
        [Test]
        public void Room2dsTest()
        {
            // TODO unit test for the property 'Room2ds'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'FloorToFloorHeight'
        /// </summary>
        [Test]
        public void FloorToFloorHeightTest()
        {
            // TODO unit test for the property 'FloorToFloorHeight'
        }
        /// <summary>
        /// Test the property 'Multiplier'
        /// </summary>
        [Test]
        public void MultiplierTest()
        {
            // TODO unit test for the property 'Multiplier'
        }

    }

}
