/* 
 * Dragonfly Model Schema
 *
 * This is the documentation for Dragonfly model schema.
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DragonflySchema;

using System.Reflection;
using Newtonsoft.Json;

namespace DragonflySchema.Test
{
    /// <summary>
    ///  Class for testing StoryEnergyPropertiesAbridged
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StoryEnergyPropertiesAbridgedTests
    {
        // TODO uncomment below to declare an instance variable for StoryEnergyPropertiesAbridged
        //private StoryEnergyPropertiesAbridged instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoryEnergyPropertiesAbridged
            //instance = new StoryEnergyPropertiesAbridged();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoryEnergyPropertiesAbridged
        /// </summary>
        [Test]
        public void StoryEnergyPropertiesAbridgedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StoryEnergyPropertiesAbridged
            //Assert.IsInstanceOf(typeof(StoryEnergyPropertiesAbridged), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ConstructionSet'
        /// </summary>
        [Test]
        public void ConstructionSetTest()
        {
            // TODO unit test for the property 'ConstructionSet'
        }

    }

}
