version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - "> 16.8.0"
  - dependency-name: Newtonsoft.Json
    versions:
    - "> 12.0.1"
  - dependency-name: NUnit
    versions:
    - "> 3.11.0"
  - dependency-name: HoneybeeSchema
    versions:
    - 1.40.2.1
    - 1.40.2.2
    - 1.40.2.3
    - 1.42.0
    - 1.42.2
    - 1.42.2.1
  commit-message:
    prefix: fix
    include: scope
