/* 
 * Dragonfly Model Schema
 *
 * Documentation for Dragonfly model schema
 *
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using HoneybeeSchema;
using System.ComponentModel.DataAnnotations;


namespace DragonflySchema
{
    /// <summary>
    /// An enumeration.
    /// </summary>
    /// <value>An enumeration.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ExteriorFaceType
    {
        /// <summary>
        /// Enum Wall for value: Wall
        /// </summary>
        [EnumMember(Value = "Wall")]
        Wall = 1,

        /// <summary>
        /// Enum Roof for value: Roof
        /// </summary>
        [EnumMember(Value = "Roof")]
        Roof = 2,

        /// <summary>
        /// Enum Floor for value: Floor
        /// </summary>
        [EnumMember(Value = "Floor")]
        Floor = 3,

        /// <summary>
        /// Enum All for value: All
        /// </summary>
        [EnumMember(Value = "All")]
        All = 4

    }

}
