/* 
 * Dragonfly Model Schema
 *
 * Documentation for Dragonfly model schema
 *
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;


namespace DragonflySchema
{
    /// <summary>
    /// OpenAPIGenBaseModel
    /// </summary>
    [DataContract(Name = "_OpenAPIGenBaseModel")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(Ground), "Ground")]
    [JsonSubtypes.KnownSubType(typeof(Overhang), "Overhang")]
    [JsonSubtypes.KnownSubType(typeof(Autocalculate), "Autocalculate")]
    [JsonSubtypes.KnownSubType(typeof(BuildingPropertiesAbridged), "BuildingPropertiesAbridged")]
    [JsonSubtypes.KnownSubType(typeof(ContextShadeEnergyPropertiesAbridged), "ContextShadeEnergyPropertiesAbridged")]
    [JsonSubtypes.KnownSubType(typeof(SimpleWindowRatio), "SimpleWindowRatio")]
    [JsonSubtypes.KnownSubType(typeof(DetailedWindows), "DetailedWindows")]
    [JsonSubtypes.KnownSubType(typeof(Surface), "Surface")]
    [JsonSubtypes.KnownSubType(typeof(FloorConstructionSet), "FloorConstructionSet")]
    [JsonSubtypes.KnownSubType(typeof(RectangularWindows), "RectangularWindows")]
    [JsonSubtypes.KnownSubType(typeof(FaceSubSetAbridged), "_FaceSubSetAbridged")]
    [JsonSubtypes.KnownSubType(typeof(VentilationOpening), "VentilationOpening")]
    [JsonSubtypes.KnownSubType(typeof(Plane), "Plane")]
    [JsonSubtypes.KnownSubType(typeof(DoorConstructionSetAbridged), "DoorConstructionSetAbridged")]
    [JsonSubtypes.KnownSubType(typeof(Room2DEnergyPropertiesAbridged), "Room2DEnergyPropertiesAbridged")]
    [JsonSubtypes.KnownSubType(typeof(Adiabatic), "Adiabatic")]
    [JsonSubtypes.KnownSubType(typeof(DatedBaseModel), "DatedBaseModel")]
    [JsonSubtypes.KnownSubType(typeof(ExtrudedBorder), "ExtrudedBorder")]
    [JsonSubtypes.KnownSubType(typeof(RepeatingWindowRatio), "RepeatingWindowRatio")]
    [JsonSubtypes.KnownSubType(typeof(WallConstructionSet), "WallConstructionSet")]
    [JsonSubtypes.KnownSubType(typeof(ApertureConstructionSetAbridged), "ApertureConstructionSetAbridged")]
    [JsonSubtypes.KnownSubType(typeof(Room2DPropertiesAbridged), "Room2DPropertiesAbridged")]
    [JsonSubtypes.KnownSubType(typeof(BuildingEnergyPropertiesAbridged), "BuildingEnergyPropertiesAbridged")]
    [JsonSubtypes.KnownSubType(typeof(ContextShadePropertiesAbridged), "ContextShadePropertiesAbridged")]
    [JsonSubtypes.KnownSubType(typeof(RoofCeilingConstructionSet), "RoofCeilingConstructionSet")]
    [JsonSubtypes.KnownSubType(typeof(StoryPropertiesAbridged), "StoryPropertiesAbridged")]
    [JsonSubtypes.KnownSubType(typeof(Outdoors), "Outdoors")]
    [JsonSubtypes.KnownSubType(typeof(Face3D), "Face3D")]
    [JsonSubtypes.KnownSubType(typeof(IDdBaseModel), "IDdBaseModel")]
    [JsonSubtypes.KnownSubType(typeof(DoorConstructionSet), "DoorConstructionSet")]
    [JsonSubtypes.KnownSubType(typeof(ModelEnergyProperties), "ModelEnergyProperties")]
    [JsonSubtypes.KnownSubType(typeof(ModelProperties), "ModelProperties")]
    [JsonSubtypes.KnownSubType(typeof(IDdEnergyBaseModel), "IDdEnergyBaseModel")]
    [JsonSubtypes.KnownSubType(typeof(NoLimit), "NoLimit")]
    [JsonSubtypes.KnownSubType(typeof(StoryEnergyPropertiesAbridged), "StoryEnergyPropertiesAbridged")]
    [JsonSubtypes.KnownSubType(typeof(SingleWindow), "SingleWindow")]
    [JsonSubtypes.KnownSubType(typeof(ApertureConstructionSet), "ApertureConstructionSet")]
    [JsonSubtypes.KnownSubType(typeof(FaceSubSet), "_FaceSubSet")]
    [JsonSubtypes.KnownSubType(typeof(LouversBase), "_LouversBase")]
    [JsonSubtypes.KnownSubType(typeof(Autosize), "Autosize")]
    [JsonSubtypes.KnownSubType(typeof(VentilationControlAbridged), "VentilationControlAbridged")]
    public partial class OpenAPIGenBaseModel : IEquatable<OpenAPIGenBaseModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OpenAPIGenBaseModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public OpenAPIGenBaseModel
        (
            // Required parameters
             // Optional parameters
        )// BaseClass
        {

            // Set non-required readonly properties with defaultValue
            this.Type = "InvalidType";
        }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "OpenAPIGenBaseModel";
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString(bool detailed)
        {
            if (!detailed)
                return this.ToString();
            
            var sb = new StringBuilder();
            sb.Append("OpenAPIGenBaseModel:\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the object from JSON string
        /// </summary>
        /// <returns>OpenAPIGenBaseModel object</returns>
        public static OpenAPIGenBaseModel FromJson(string json)
        {
            var obj = JsonConvert.DeserializeObject<OpenAPIGenBaseModel>(json, JsonSetting.AnyOfConvertSetting);
            if (obj == null)
                return null;
            return obj.Type.ToLower() == obj.GetType().Name.ToLower() ? obj : null;
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>OpenAPIGenBaseModel object</returns>
        public virtual OpenAPIGenBaseModel DuplicateOpenAPIGenBaseModel()
        {
            return FromJson(this.ToJson());
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>OpenAPIGenBaseModel</returns>
        public override OpenAPIGenBaseModel Duplicate()
        {
            return DuplicateOpenAPIGenBaseModel();
        }

     
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OpenAPIGenBaseModel);
        }

        /// <summary>
        /// Returns true if OpenAPIGenBaseModel instances are equal
        /// </summary>
        /// <param name="input">Instance of OpenAPIGenBaseModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OpenAPIGenBaseModel input)
        {
            if (input == null)
                return false;
            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
