//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace DragonflySchema
{
	public partial interface IShading_Parameter {}
}

//Classes implemented this interface:
namespace DragonflySchema
{
	public partial class ExtrudedBorder: DragonflySchema.IShading_Parameter {}
	public partial class LouversByCount: DragonflySchema.IShading_Parameter {}
	public partial class LouversByDistance: DragonflySchema.IShading_Parameter {}
	public partial class Overhang: DragonflySchema.IShading_Parameter {}
}
