//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace DragonflySchema
{
	public partial interface IWindow_Parameter {}
}

//Classes implemented this interface:
namespace DragonflySchema
{
	public partial class DetailedWindows: DragonflySchema.IWindow_Parameter {}
	public partial class RectangularWindows: DragonflySchema.IWindow_Parameter {}
	public partial class RepeatingWindowRatio: DragonflySchema.IWindow_Parameter {}
	public partial class SimpleWindowArea: DragonflySchema.IWindow_Parameter {}
	public partial class SimpleWindowRatio: DragonflySchema.IWindow_Parameter {}
	public partial class SingleWindow: DragonflySchema.IWindow_Parameter {}
}
