//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace DragonflySchema.Radiance
{
	public partial interface IGridpar {}
}

//Classes implemented this interface:
namespace DragonflySchema
{
	public partial class ExteriorApertureGridParameter: DragonflySchema.Radiance.IGridpar {}
	public partial class ExteriorFaceGridParameter: DragonflySchema.Radiance.IGridpar {}
	public partial class RoomGridParameter: DragonflySchema.Radiance.IGridpar {}
	public partial class RoomRadialGridParameter: DragonflySchema.Radiance.IGridpar {}
}
