//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace DragonflySchema.Radiance
{
	public partial interface IProperties {}
}

//Classes implemented this interface:
namespace DragonflySchema
{
	public partial class BuildingRadiancePropertiesAbridged: DragonflySchema.Radiance.IProperties {}
	public partial class ContextShadeRadiancePropertiesAbridged: DragonflySchema.Radiance.IProperties {}
	public partial class ModelRadianceProperties: DragonflySchema.Radiance.IProperties {}
	public partial class Room2DRadiancePropertiesAbridged: DragonflySchema.Radiance.IProperties {}
	public partial class StoryRadiancePropertiesAbridged: DragonflySchema.Radiance.IProperties {}
}
