/* 
 * Dragonfly Model Schema
 *
 * This is the documentation for Dragonfly model schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DragonflyDotNet;

using System.Reflection;
using Newtonsoft.Json;

namespace DragonflyDotNet.Test
{
    /// <summary>
    ///  Class for testing LouversByCount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LouversByCountTests
    {
        // TODO uncomment below to declare an instance variable for LouversByCount
        //private LouversByCount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LouversByCount
            //instance = new LouversByCount();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LouversByCount
        /// </summary>
        [Test]
        public void LouversByCountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" LouversByCount
            //Assert.IsInstanceOf(typeof(LouversByCount), instance);
        }


        /// <summary>
        /// Test the property 'Depth'
        /// </summary>
        [Test]
        public void DepthTest()
        {
            // TODO unit test for the property 'Depth'
        }
        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Test]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
        /// <summary>
        /// Test the property 'Angle'
        /// </summary>
        [Test]
        public void AngleTest()
        {
            // TODO unit test for the property 'Angle'
        }
        /// <summary>
        /// Test the property 'ContourVector'
        /// </summary>
        [Test]
        public void ContourVectorTest()
        {
            // TODO unit test for the property 'ContourVector'
        }
        /// <summary>
        /// Test the property 'FlipStartSide'
        /// </summary>
        [Test]
        public void FlipStartSideTest()
        {
            // TODO unit test for the property 'FlipStartSide'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'LouverCount'
        /// </summary>
        [Test]
        public void LouverCountTest()
        {
            // TODO unit test for the property 'LouverCount'
        }

    }

}
