/* 
 * Dragonfly Model Schema
 *
 * This is the documentation for Dragonfly model schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DragonflyDotNet;

using System.Reflection;
using Newtonsoft.Json;

namespace DragonflyDotNet.Test
{
    /// <summary>
    ///  Class for testing RepeatingWindowRatio
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RepeatingWindowRatioTests
    {
        // TODO uncomment below to declare an instance variable for RepeatingWindowRatio
        //private RepeatingWindowRatio instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RepeatingWindowRatio
            //instance = new RepeatingWindowRatio();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RepeatingWindowRatio
        /// </summary>
        [Test]
        public void RepeatingWindowRatioInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RepeatingWindowRatio
            //Assert.IsInstanceOf(typeof(RepeatingWindowRatio), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'WindowRatio'
        /// </summary>
        [Test]
        public void WindowRatioTest()
        {
            // TODO unit test for the property 'WindowRatio'
        }
        /// <summary>
        /// Test the property 'WindowHeight'
        /// </summary>
        [Test]
        public void WindowHeightTest()
        {
            // TODO unit test for the property 'WindowHeight'
        }
        /// <summary>
        /// Test the property 'SillHeight'
        /// </summary>
        [Test]
        public void SillHeightTest()
        {
            // TODO unit test for the property 'SillHeight'
        }
        /// <summary>
        /// Test the property 'HorizontalSeparation'
        /// </summary>
        [Test]
        public void HorizontalSeparationTest()
        {
            // TODO unit test for the property 'HorizontalSeparation'
        }
        /// <summary>
        /// Test the property 'VerticalSeparation'
        /// </summary>
        [Test]
        public void VerticalSeparationTest()
        {
            // TODO unit test for the property 'VerticalSeparation'
        }

    }

}
