/* 
 * Dragonfly Model Schema
 *
 * This is the documentation for Dragonfly model schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DragonflyDotNet;

using System.Reflection;
using Newtonsoft.Json;

namespace DragonflyDotNet.Test
{
    /// <summary>
    ///  Class for testing Room2DPropertiesAbridged
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Room2DPropertiesAbridgedTests
    {
        // TODO uncomment below to declare an instance variable for Room2DPropertiesAbridged
        //private Room2DPropertiesAbridged instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Room2DPropertiesAbridged
            //instance = new Room2DPropertiesAbridged();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Room2DPropertiesAbridged
        /// </summary>
        [Test]
        public void Room2DPropertiesAbridgedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Room2DPropertiesAbridged
            //Assert.IsInstanceOf(typeof(Room2DPropertiesAbridged), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Energy'
        /// </summary>
        [Test]
        public void EnergyTest()
        {
            // TODO unit test for the property 'Energy'
        }

    }

}
