/* 
 * Dragonfly Model Schema
 *
 * This is the documentation for Dragonfly model schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DragonflyDotNet;

using System.Reflection;
using Newtonsoft.Json;

namespace DragonflyDotNet.Test
{
    /// <summary>
    ///  Class for testing Room2D
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Room2DTests
    {
        // TODO uncomment below to declare an instance variable for Room2D
        //private Room2D instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Room2D
            //instance = new Room2D();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Room2D
        /// </summary>
        [Test]
        public void Room2DInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Room2D
            //Assert.IsInstanceOf(typeof(Room2D), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'FloorBoundary'
        /// </summary>
        [Test]
        public void FloorBoundaryTest()
        {
            // TODO unit test for the property 'FloorBoundary'
        }
        /// <summary>
        /// Test the property 'FloorHoles'
        /// </summary>
        [Test]
        public void FloorHolesTest()
        {
            // TODO unit test for the property 'FloorHoles'
        }
        /// <summary>
        /// Test the property 'FloorHeight'
        /// </summary>
        [Test]
        public void FloorHeightTest()
        {
            // TODO unit test for the property 'FloorHeight'
        }
        /// <summary>
        /// Test the property 'FloorToCeilingHeight'
        /// </summary>
        [Test]
        public void FloorToCeilingHeightTest()
        {
            // TODO unit test for the property 'FloorToCeilingHeight'
        }
        /// <summary>
        /// Test the property 'IsGroundContact'
        /// </summary>
        [Test]
        public void IsGroundContactTest()
        {
            // TODO unit test for the property 'IsGroundContact'
        }
        /// <summary>
        /// Test the property 'IsTopFloor'
        /// </summary>
        [Test]
        public void IsTopFloorTest()
        {
            // TODO unit test for the property 'IsTopFloor'
        }
        /// <summary>
        /// Test the property 'BoundaryConditions'
        /// </summary>
        [Test]
        public void BoundaryConditionsTest()
        {
            // TODO unit test for the property 'BoundaryConditions'
        }
        /// <summary>
        /// Test the property 'WindowParameters'
        /// </summary>
        [Test]
        public void WindowParametersTest()
        {
            // TODO unit test for the property 'WindowParameters'
        }
        /// <summary>
        /// Test the property 'ShadingParameters'
        /// </summary>
        [Test]
        public void ShadingParametersTest()
        {
            // TODO unit test for the property 'ShadingParameters'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

    }

}
