/* 
 * Dragonfly Model Schema
 *
 * This is the documentation for Dragonfly model schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DragonflyDotNet;

using System.Reflection;
using Newtonsoft.Json;

namespace DragonflyDotNet.Test
{
    /// <summary>
    ///  Class for testing SingleWindow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SingleWindowTests
    {
        // TODO uncomment below to declare an instance variable for SingleWindow
        //private SingleWindow instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SingleWindow
            //instance = new SingleWindow();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SingleWindow
        /// </summary>
        [Test]
        public void SingleWindowInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SingleWindow
            //Assert.IsInstanceOf(typeof(SingleWindow), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'SillHeight'
        /// </summary>
        [Test]
        public void SillHeightTest()
        {
            // TODO unit test for the property 'SillHeight'
        }

    }

}
